[tox]
isolated_build = true
envlist = py311,py312
requires =
    tox-uv>=1

[testenv]
runner = uv-venv-lock-runner
with_dev = true
allowlist_externals =
    uv
    docker
    docker-compose
passenv =
    SSH_AUTH_SOCK
    SKIP
commands =
    uv run docker/pre_commit_init.sh  # also runs pre-commit
    uv run pytest --junitxml=pytest-{envname}.xml tests/
    # if pre-commit does not run these (or you don't run pre-commit here) enable at least these checks
    # mypy src tests
    # pylint src tests
    # bandit --skip=B101 -r src
