on:
    pull_request:

jobs:
  versiontag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pvarki/config-ci-library/.github/actions/validate-bumpversion@main

  test:
    runs-on: arc-runner-set
    permissions:
      contents: write
      pull-requests: write
      checks: write
    strategy:
      matrix:
        python-version: ["3.11"] # , "3.12"]
    env:
      PIP_INDEX_URL: https://nexus.dev.pvarki.fi/repository/python/simple
      UV_DEFAULT_INDEX: https://nexus.dev.pvarki.fi/repository/python/simple
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: pvarki/config-ci-library/.github/actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Do pre-commit checks (black, lint, mypy)
        run: |
          uv run docker/pre_commit_init.sh
      - name: Prep docker
        run: |
          rm -rf api/tests/data/cfssl/*
          rm -rf api/tests/data/ca_public/*
          docker system prune --all --volumes --force
          cd tests
          docker compose -f docker-compose.yml pull --ignore-pull-failures
          docker compose -f docker-compose.yml up -d --wait || docker compose -f docker-compose.yml logs
          docker compose -f docker-compose.yml down -v
      - name: Test with pytest
        run: |
          uv run py.test -v --junitxml=pytest.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/pytest*.xml'
          detailed_summary: true
          check_name: 'JUnit report (local)'

  docker_builds:
    runs-on: arc-runner-set
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Build test target
        run: docker build --target test -t rmapi:test .
      - name: Build production target
        run: docker build --target production -t rmapi:production .
