on:
    pull_request:
    push:
      branches-ignore:
        - main

jobs:
    tox:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - run: eval "$(ssh-agent -s)" && export DOCKER_BUILDKIT=1 && docker build --ssh default --target tox -t rasenmaeher_api:tox .
      - run: docker run --rm -v ${{ github.workspace }}:/app -v $SSH_AUTH_SOCK:$SSH_AUTH_SOCK -e SSH_AUTH_SOCK rasenmaeher_api:tox

    devel_shell:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - run: eval "$(ssh-agent -s)" && export DOCKER_BUILDKIT=1 && docker build --ssh default --target devel_shell -t rasenmaeher_api:devel_shell .
      - run: docker run --rm -v ${{ github.workspace }}:/app -v $SSH_AUTH_SOCK:$SSH_AUTH_SOCK -e SSH_AUTH_SOCK rasenmaeher_api:devel_shell
