on:
  push:
    branches:
      - main

jobs:
  snyk_monitor:
    name: Run Snyk monitor
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: pvarki/config-ci-library/.github/actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
      - uses: pvarki/config-ci-library/.github/actions/snyk-monitor@main
        with:
          snyk-org: deployapp-core-services
          snyk-token: ${{ secrets.SNYK_TOKEN }}

  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Publish Docker image
        uses: pvarki/config-ci-library/.github/actions/publish-image@main
        with:
          product: rasenmaeher
          component: api
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          acr-repo: ${{ vars.ACR_REPO }}
          acr-username: ${{ vars.ACR_USERNAME }}
          acr-token: ${{ secrets.ACR_TOKEN }}
