name: Create tag for release

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main

jobs:
  tag_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Parse tag to ENV
        run: |
          echo RELEASE_TAG=$(docker run --rm -v ${PWD}:/workdir mikefarah/yq .version version.yml ) >> ${GITHUB_ENV}
          cat ${GITHUB_ENV}
      - uses: rickstaa/action-create-tag@v1
        if: ${{ !env.ACT }}
        id: "tag_create"
        with:
          tag: ${{ env.RELEASE_TAG }}
          tag_exists_error: false
